name: Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk_audit:
    name: Snyk Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SAST scan with Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  npm_audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Vulnerability scan with npm audit
        run: yarn npm audit

      - name: Provenance scan with npm audit
        run: yarn npm audit signatures

  yarn_audit:
    name: Yarn Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Vulnerability scan with yarn audit
        run: yarn audit
