exclude: "^(.*egg.info.*).*$"
repos:

  ################
  # Linters
  ################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: mixed-line-ending
        args: [ --fix, auto ]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-byte-order-marker
      - id: check-toml
      - id: check-yaml

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        exclude: >
          (?x)^(
              .git/COMMIT_EDITMSG
          )$

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: text-unicode-replacement-char

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        args:
          - '--fix'
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [ file ]

  ################
  # SAST
  ################
  - repo: https://github.com/returntocorp/semgrep
    rev: 'v1.55.0'
    hooks:
      - id: semgrep-ci


  ################
  # Secrets
  ################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - --allow-missing-credential

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline' ]

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.1
    hooks:
      - id: gitleaks


  ################
  # Git
  ################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
#      - id: no-commit-to-branch

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
