nodeLinker: node-modules
enableColors: true
enableHyperlinks: true
enableConstraintsChecks: true
enableHardenedMode: true
enableStrictSsl: true
enableGlobalCache: false
enableMirror: false
enableScripts: false
enableTelemetry: false
enableImmutableCache: false
supportedArchitectures:
  os:
    - darwin
    - linux
